[project]
name = "data-job-ad-nlp-de"
version = "0.1.0"
description = "What do German employers want from data people? NLP analysis of job ads from the Bundesagentur für Arbeit. Was erwarten deutsche Arbeitgeber von Datenleuten? NLP-Analyse von Stellenanzeigen der Bundesagentur für Arbeit."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.0.1",
    "kagglehub>=0.3.13",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "seaborn>=0.13.2",
    "duckdb>=1.4.1",
    "scikit-learn>=1.7.2",
]

[build-system]
requires = ["uv_build>=0.8.9,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "core"
